name: alhayaa_news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.0
  dio: ^5.9.0
  url_launcher: 6.2.2
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.3.0
  carousel_slider: ^5.1.1
  intl: ^0.17.0
  dartz: ^0.10.1
  shared_preferences: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0



flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/play_store_512.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Regular.ttf


